services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      env_file:
        - .env
      args:
        # Build-time variables if needed
        - NODE_ENV=production
    container_name: frontend-budokanryu
    env_file:
      - .env
    environment:
      # Explicit environment variables (optional, since you're using .env file)
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - '3000:3000'
    volumes:
      # For production, you might want to remove the source code volume
      # and only keep node_modules volume for better security
      - /opt/budokan-fe/node_modules
      # Uncomment below for development
      # - ./:/opt/budokan-fe
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Add resource limits for production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

networks:
  swag_default:
    name: swag_default
    external: true
