services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-budokanryu
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  swag_default:
    name: swag_default
    driver: bridge
