name: PR Validation

on:
  pull_request:
    branches:
      - main   # PR target branch
    paths-ignore:
      - '**.md' # optional, ignore docs-only PRs
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate code (lint & build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '10.0.0'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint

      - name: Run build
        run: pnpm run build
